### PR TITLE
add seconds option to interval_units with tests

### LINKED ISSUE #28: Add `seconds` as a option RepeatableJob.UNITS
As a user, I would like to set second as a job scheduler option.

### PR DESCRIPTION
**Pull request by mattjegan**
Fixes #28 

* Adds the `'seconds'` option to `RepeatableJob.UNITS`
* Adds test for seconds unit
* Adds ignore rules for Pipfile so I didn't clutter the repo

### CODE REVIEW

**Comment by mattjegan** [comment]
Thanks for the review @tom-price, that's a good point about confusion. If a user was to schedule a task every x seconds they would need to run rq-scheduler like so: `rqscheduler -i x` to adjust for the default per minute checking of tasks. Would a note in the README be of use?

**Comment by tom-price** [comment]
I'm still torn on this. So adding seconds with a 

I don't think your suggestion of how to update the readme fits. The `get_scheduler` function defined in Django-RQ shown below allows for the interval to be passed in when called by Django-RQ-Scheduler, but so currently there's no way to pass in that interval value. It's not like it's a parameter you can add to `RQ_QUEUES`.
```   
def get_scheduler(name='default', interval=60):
        """
        Returns an RQ Scheduler instance using parameters defined in
        ``RQ_QUEUES``
        """
        return Scheduler(name, interval=interval,
                         connection=get_connection(name))
```

I also don't think that failing silently is an option if the interval set on the job is lower than the scheduler's interval, or maybe isn't even a multiple of the interval frequency (unsure about that part).

In `RepeatableJob` functions like these below could be added to throw an error if a save is attempted that violates these conditions; however, the example below relies on a protected member of  RQ_Scheduler's `Scheduler` class and `self.scheduler` would need to be modified to pass in an interval if one other than the default was set, which means you could pull from there if wanting one below 60. I'm going to keep thinking about this.
```
    def clean(self):
        super(RepeatableJob, self).clean()
        self.clean_interval()

    def clean_interval(self):
        if self.scheduler()._interval > self.interval_seconds():
            raise ValidationError({
                'interval_unit': ValidationError(
                    _("job interval is set lower than queue's interval"), code='invalid')
            })
```

**Review by g3rd — APPROVED** [review]

**Comment by g3rd** [comment]
I think the code looks good.
Would like to see some documentation with a disclaimer.

**Comment by mattjegan** [comment]
@g3rd Thanks for checking this out, do you think the rq-scheduler interval issue needs to be fixed by this PR or just a disclaimer before this is merged?

**Comment by mattjegan** [comment]
@g3rd The rq-scheduler interval issue has been resolved on this PR by @tom-price 

If everything looks good could you please merge.

**Review by tom-price — CHANGES_REQUESTED** [review]
Unfortunately this merge cbd6d130921e52ff3fcd650350e50705a417c856 introduced a 2nd migration **0006**_{migration name}.py breaking this PR.

**Comment by mattjegan** [comment]
@tom-price I have merged in your PR that resolves the duplicate migration. At @divipayhq we have been running this branch in production for nearly 12 months and have not seen any issues with the interval being in the realm of a few seconds. I'd love to see this released as the next version, please let me know if anything is needed @g3rd

**Pull request closed without merging**
