### PR TITLE
Delete takes care of unscheduling

### PR DESCRIPTION
**Pull request by tom-price**
A revised version of PR #20 simplified to only include revisions to how deletion works (no admin validation on time) that'll be safe to merge after PR #22.

### CODE REVIEW

**Comment by tom-price** [comment]
Wasn't sure the best way to submit this PR as its tests fail without the revisions present in #22, though not for any reasons related to the code changes relevant to this PR.

**Comment by oudeismetis** [comment]
@tom-price Some great work!
Would you like to be added as a maintainer for this project?

After we update the README and get a new pypi version out there, @bashhack and I are going to continue to keep an eye on this project for issues and PRs, but it's not going to be a high priority for us.

I think the 3 of us together could easily make sure this project stays relevant and up to date with it's current features.

**Comment by tom-price** [comment]
Sure, I'd be happy to help. I'm using this as part of a longer term project of my own so I'll also be paying attention to it, rq-scheduler, etc..

As a heads up, I've been working on adding args and kwargs support and will hopefully finish sometime later this week.

**Comment by jteppinette** [comment]
@oudeismetis @tom-price Is `django-rq-scheduler` going to be updated on PyPI?

**Comment by tom-price** [comment]
@jteppinette, Unfortunately I'm not sure. I've not been in touch with the other maintainers and I've not done that part before. I've got a couple changes ready to go and continue to use a fork of this project on a daily basis in my own work, so it's not forgotten about.

**Comment by jteppinette** [comment]
@tom-price It looks like someone is maintaining a separate PyPI package with this update and .. something else .. (1.1.3).

https://pypi.org/project/readwise-django-rq-scheduler/#description

**Comment by tom-price** [comment]
Interesting. I'll make a renewed effort to get in touch with the other maintainers. There are some outstanding PRs including my own, #24, that seem ready, or would be with little work, for merging in and publishing.

**Comment by jteppinette** [comment]
@oudeismetis @tom-price We should update PyPI ownership on this package. I am using this package at work, so I would be willing to do it.

**Pull request merged**
