### PR TITLE
Enable configuration of result_ttl in django-rq-scheduler

### PR DESCRIPTION
**Pull request by frbry**
Currently all scheduled and repeatable tasks are created with `result_ttl=-1`. This causes `Result will never expire, clean up result key manually` warnings to be logged, which can be annoying.

This PR creates a new field in `BaseTask` model so the user has the ability to change `result_ttl` value for newly created RQ tasks.

Note: `result_ttl` defaults to -1, which is weird because the RQ docs say it's 500 seconds by default: http://python-rq.org/docs/results/

### CODE REVIEW

**Comment by frbry** [comment]
Hi @g3rd, any chance you could take a look at this one? Thanks! :)

**Comment by frbry** [comment]
Hi @g3rd, any feedback?

**Comment by oudeismetis** [comment]
@frbry 
Sorry for the slow reply on this.
At a high level this looks good. Going to pull this down and check it out, but I expect this will be merged soon.

Thanks for thinking of this!

**Comment by tom-price** [comment]
@oudeismetis, I've created PR #22 to merge @frbry's work into the project as there were minor issues related to the introduction of cron jobs.

**Comment by frbry** [comment]
Thanks @oudeismetis and @tom-price!

**Pull request merged**
