### PR TITLE
fix QueueMixin - obj can be None

### PR DESCRIPTION
**Pull request by chassing**
obj can be None and it throws an "AttributeError: 'NoneType' object has no attribute '_meta'"

### CODE REVIEW

**Comment by koslibpro** [comment]
is it merged?

**Comment by jcarbaugh** [comment]
@chassing @koslibpro sorry for the delay in merging! This looks great. The contribution is very much appreciated!

The package author, @g3rd, is out today, so I'll ask him to put out a new release to PyPI tomorrow.

**Comment by jcarbaugh** [comment]
@chassing @koslibpro v1.1.1 was just released to PyPI by @g3rd 

https://pypi.python.org/pypi/django-rq-scheduler/1.1.1

**Comment by koslibpro** [comment]
That's great and hugely anticipated news! Thanks @jcarbaugh!

**Pull request merged**
